version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: server/script/start.sh
      timeout: 60
      runas: root