version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/server/ #디렉터리명 
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu