version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/server/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /home/ubuntu/server/scripts/start.sh
      timeout: 60
      runas: ubuntu