version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - mvn spotless:apply #안되면 삭제
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
      #- aws s3 cp target/webgoat-2023.6-SNAPSHOT.jar s3://codebuild-artifact-output-s3/output/
      #- aws s3 cp buildspec_owasp_dependency_check.yml s3://codebuild-artifact-output-s3/output/
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - script/start.sh
    - buildspec_owasp_dependency_check.yml